apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
     # - image: devakumaran/images:latest1
     # - image: kammana/nodeapp:v2
      - image: kammana/node-app:ef8ec721ca8f01f3152fe76068915d6c6a007d3c
        name: nodeapp
        ports:
        - containerPort: 8080
